/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaLog.java
 *
 * Created on 09/10/2011, 19:20:41
 */
package br.com.mailanalyzer.grafico;

import br.com.mailanalyzer.dao.LogDAO;
import br.com.mailanalyzer.domain.Log;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author McLuck
 */
public class ListaLog extends javax.swing.JFrame {

    /** Creates new form ListaLog */
    public ListaLog() {
        initComponents();
    }
    private int intervalo, registros;

    private void setContentInputs() {
        input_intervalo.setText(String.valueOf(intervalo));
        input_qtd.setText(String.valueOf(registros));
    }

    private void setDefaultInputs() {
        intervalo = 5;
        registros = 100;
        setContentInputs();
    }

    private boolean lerInputs() {
        String qtd = input_qtd.getText();
        try {
            registros = Integer.parseInt(qtd);
        } catch (Exception e) {
            error_qtd.setText("Quantidade de registros inválida!");
            return false;
        }

        String inter = input_intervalo.getText();
        try {
            intervalo = Integer.parseInt(inter);
        } catch (Exception e) {
            error_qtd.setText("Intervalo inválido!");
            return false;
        }

        if (registros > 1000 || registros < 1) {
            error_qtd.setText("Quantidade de registros inválida!");
            return false;
        }

        if (intervalo > (1000) || intervalo < 3) {
            error_qtd.setText("Intervalo inválido. Só é permitido intervalo entre 3 e 1000 segundos!");
            return false;
        }
        return true;
    }
    private void loadLista(){
        if(logs==null){
            logs = new ArrayList<Log>();
        }
        if(!lerInputs()){
            return;
        }
        ldao.setQtdRegistro(registros);
        logs = ldao.obterTodos();
    }
    private static LogDAO ldao = new LogDAO();
    private List<Log> logs;
    private ListaLog model;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        input_qtd = new javax.swing.JTextField();
        error_qtd = new javax.swing.JLabel();
        input_intervalo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_aplicar = new javax.swing.JButton();
        info = new javax.swing.JCheckBox();
        debug = new javax.swing.JCheckBox();
        aviso = new javax.swing.JCheckBox();
        erro = new javax.swing.JCheckBox();
        fatal = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        input_src_tag = new javax.swing.JTextField();
        input_src_referencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_src_referencia1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Quando", "Ocorrência", "TAG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bt_fechar.setText("Fechar");

        jLabel1.setText("Quantidade:");

        input_qtd.setText("100");

        error_qtd.setForeground(new java.awt.Color(153, 0, 0));
        error_qtd.setText(".");

        input_intervalo.setText("5");

        jLabel2.setText("Intervalo:");

        bt_aplicar.setText("Aplicar Filtro");

        info.setSelected(true);
        info.setText("INFO");

        debug.setSelected(true);
        debug.setText("DEBUG");

        aviso.setSelected(true);
        aviso.setText("AVISO");

        erro.setSelected(true);
        erro.setText("ERRO");

        fatal.setSelected(true);
        fatal.setText("ERRO FATAL");

        jLabel3.setText("Buscar TAG:");

        jLabel4.setText("Buscar TAG:");

        jLabel5.setText("Filtro detalhe:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(376, 376, 376)
                        .add(bt_fechar))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(error_qtd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 305, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(input_qtd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(info)
                                .add(13, 13, 13)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(erro)
                                        .add(18, 18, 18)
                                        .add(jLabel3)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(input_src_tag, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(aviso)
                                        .add(18, 18, 18)
                                        .add(fatal)))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(input_src_referencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 41, Short.MAX_VALUE)
                                        .add(bt_aplicar))
                                    .add(input_src_referencia1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(input_intervalo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(debug)
                .addContainerGap(794, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(error_qtd)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel1)
                                    .add(input_qtd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(info)
                                    .add(aviso)
                                    .add(fatal)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(input_src_referencia1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel5))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel2)
                                    .add(input_intervalo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(debug)
                                    .add(erro)
                                    .add(jLabel3)
                                    .add(input_src_tag, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel4)
                                    .add(input_src_referencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(bt_aplicar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 354, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(bt_fechar)
                .add(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListaLog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aviso;
    private javax.swing.JButton bt_aplicar;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JCheckBox debug;
    private javax.swing.JCheckBox erro;
    private javax.swing.JLabel error_qtd;
    private javax.swing.JCheckBox fatal;
    private javax.swing.JCheckBox info;
    private javax.swing.JTextField input_intervalo;
    private javax.swing.JTextField input_qtd;
    private javax.swing.JTextField input_src_referencia;
    private javax.swing.JTextField input_src_referencia1;
    private javax.swing.JTextField input_src_tag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
